### PR TITLE
Fixed issue #14 Update request headers

### LINKED ISSUE #14: Update request headers
Add OS and app version as a headers for each request that is send to the backend.

### PR DESCRIPTION
**Pull request by IvanYuliyanov**
Added User-Agent request header with information about the app name, version, operation system and device model.

### CODE REVIEW

File: service/src/main/java/com/upnetix/applicationservice/base/HeaderInterceptor.kt [hunk 1]
```diff
@@ -48,9 +52,21 @@ class HeaderInterceptor @Inject constructor(
 		proceed(requestBuilder.build())
 	}
 
+	private fun createUserAgent(): String {
+		var userAgent = "${context.getString(R.string.app_name)}/${BuildConfig.VERSION_CODE}"
+		val baseUserAgent = System.getProperty(USER_AGENT_SYSTEM_PROPERTY)
+		baseUserAgent?.let {
+			userAgent = "$userAgent $baseUserAgent"
```
Comment (s-yanev) [inline service/src/main/java/com/upnetix/applicationservice/base/HeaderInterceptor.kt]: You can use $it insted of $baseUserAgent and directly return from the let so you don't need to reassign the value.

Comment (IvanYuliyanov) [reply service/src/main/java/com/upnetix/applicationservice/base/HeaderInterceptor.kt]: Done.

**Review by s-yanev — APPROVED** [review]
